---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos_instance
    image: gamer9460/centos_systemd:latest
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    cgroupns_mode: private
    override_command: false
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /tmp
      - /run/lock
